const button=document.querySelector('.menu-button');const nav=document.querySelector('#site-nav');button?.addEventListener('click',()=>{const open=button.getAttribute('aria-expanded')==='true';button.setAttribute('aria-expanded',String(!open));nav.classList.toggle('open',!open)});nav?.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');button?.setAttribute('aria-expanded','false')}));

// 幹事レビュー用。実運用ではCloudflare Workers APIに置き換え、名簿をブラウザへ配信しない。
const surnames=['青海','白浜','朝倉','風間','若松','水城','浜崎','森川','大空','西浦','花田','月岡','神崎','南野','高瀬','春日','波多野','小森','有村','松永','岩崎','川瀬','藤森','北原','星野','橘','早川','望月','宮原','日高'];
const givenNames=['海斗','美咲','陽介','奈緒','健太','彩花','亮平','由佳','拓海','真紀','航','麻衣','大輔','千尋','直樹','明日香','悠人','香織','和也','沙織','翔太','優子','浩平','恵','駿','里奈','隆史','愛','誠','佳奈'];
const schools=['加也小','引津小','桜野小','不明'];const teachers=['山先生（架空）','海先生（架空）','森先生（架空）','空先生（架空）'];
const dummyRoster=surnames.map((surname,index)=>({id:`D${String(index+1).padStart(4,'0')}`,surname,givenName:givenNames[index],school:schools[index%4],classroom:`${index%4+1}組`,teacher:teachers[index%4]}));
const storageKey='shima-reunion-dummy-responses-v1';const answered=()=>new Set(JSON.parse(localStorage.getItem(storageKey)||'[]'));const mask=name=>name.length<=1?'＊':`${name[0]}${'＊'.repeat(Math.max(1,name.length-2))}${name.at(-1)}`;
const searchForm=document.querySelector('#person-search-form'),intentForm=document.querySelector('#intent-form'),message=document.querySelector('#form-message'),candidateArea=document.querySelector('#candidate-area'),candidateList=document.querySelector('#candidate-list'),selectedPerson=document.querySelector('#selected-person'),completion=document.querySelector('#completion');let selected=null;
function setMessage(text,type='info'){message.textContent=text;message.className=`form-message ${type}`}
function showSearch(){selected=null;intentForm.hidden=true;completion.hidden=true;candidateArea.hidden=true;searchForm.hidden=false;setMessage('')}
function selectCandidate(person){if(answered().has(person.id)){setMessage('この情報では受付できませんでした。入力内容をご確認いただくか、幹事へお問い合わせください。','error');return}selected=person;selectedPerson.textContent=`${mask(person.surname)} ${mask(person.givenName)}・${person.classroom}・${person.teacher}`;candidateArea.hidden=true;intentForm.hidden=false;setMessage('候補を選択しました。参加意向を回答してください。','success');intentForm.scrollIntoView({behavior:'smooth',block:'center'})}
searchForm?.addEventListener('submit',event=>{event.preventDefault();const school=document.querySelector('#school').value,classroom=document.querySelector('#classroom').value,teacher=document.querySelector('#teacher').value,query=document.querySelector('#name-query').value.trim().replace(/\s/g,'');const matches=dummyRoster.filter(person=>person.school===school&&person.classroom===classroom&&person.teacher===teacher&&`${person.surname}${person.givenName}`.includes(query)).slice(0,3);intentForm.hidden=true;completion.hidden=true;candidateList.replaceChildren();if(!matches.length){candidateArea.hidden=true;setMessage('候補が見つかりませんでした。選択内容や氏名の一部を確認してください。','error');return}matches.forEach(person=>{const candidate=document.createElement('button');candidate.type='button';candidate.className='candidate';candidate.innerHTML=`<strong>${mask(person.surname)} ${mask(person.givenName)}</strong><span>${person.school}・${person.classroom}・${person.teacher}</span>`;candidate.addEventListener('click',()=>selectCandidate(person));candidateList.append(candidate)});candidateArea.hidden=false;setMessage(`${matches.length}件の候補が見つかりました。`,'success')});
intentForm?.addEventListener('submit',event=>{event.preventDefault();if(!selected)return;const intent=new FormData(intentForm).get('intent');if(!intent||!document.querySelector('#privacy-agreement').checked)return;const ids=answered();ids.add(selected.id);localStorage.setItem(storageKey,JSON.stringify([...ids]));intentForm.hidden=true;searchForm.hidden=true;candidateArea.hidden=true;completion.hidden=false;setMessage('');completion.querySelector('p').textContent=`「${intent}」として受け付けました。これは体験版のため、回答はスプレッドシートへ送信されません。`;completion.scrollIntoView({behavior:'smooth',block:'center'})});
document.querySelector('#back-to-search')?.addEventListener('click',showSearch);document.querySelector('#try-again')?.addEventListener('click',()=>{searchForm.reset();intentForm.reset();showSearch()});
